#!/bin/bash
# Move current workspace to next/previous monitor

# Get current workspace
CURRENT_WS=$(hyprctl activeworkspace -j | jq -r '.id')

# Get list of monitor names
MONITORS=($(hyprctl monitors -j | jq -r '.[].name'))
CURRENT_MONITOR=$(hyprctl activeworkspace -j | jq -r '.monitor')

# Find current monitor index
CURRENT_INDEX=0
for i in "${!MONITORS[@]}"; do
    if [ "${MONITORS[$i]}" = "$CURRENT_MONITOR" ]; then
        CURRENT_INDEX=$i
        break
    fi
done

# Calculate next monitor index
MONITOR_COUNT=${#MONITORS[@]}
if [ "$1" = "next" ]; then
    NEXT_INDEX=$(((CURRENT_INDEX + 1) % MONITOR_COUNT))
else
    NEXT_INDEX=$(((CURRENT_INDEX - 1 + MONITOR_COUNT) % MONITOR_COUNT))
fi

# Get next monitor name
NEXT_MONITOR="${MONITORS[$NEXT_INDEX]}"

# Don't move if it's the same monitor
if [ "$NEXT_MONITOR" != "$CURRENT_MONITOR" ]; then
    hyprctl dispatch moveworkspacetomonitor $CURRENT_WS $NEXT_MONITOR
fi