#!/bin/bash

current_window=$(hyprctl activewindow -j 2>/dev/null)
if [[ $? -ne 0 || $(jq -r '.address' <<<"$current_window") == "null" ]]; then
    hyprctl dispatch 'hl.dsp.focus({ workspace = "-1" })'
    exit 0
fi

current_pos=$(jq -r '.at[0]' <<<"$current_window")
current_workspace=$(jq -r '.workspace.id' <<<"$current_window")
leftmost_pos=$(hyprctl clients -j | jq -r ".[] | select(.workspace.id == $current_workspace) | .at[0]" | sort -n | head -1)

if [[ "$current_pos" == "$leftmost_pos" ]]; then
    hyprctl dispatch 'hl.dsp.focus({ workspace = "-1" })'
else
    hyprctl dispatch 'hl.dsp.focus({ direction = "l" })'
fi
