#!/bin/bash

monitor1=$(hyprctl activeworkspace -j | jq -r '.monitor')
workspace1=$(hyprctl activeworkspace -j | jq -r '.id')
[[ "$workspace1" -ge 0 ]] || exit 0

monitor2=$(hyprctl monitors -j | jq -r --arg current "$monitor1" '.[] | select(.name != $current) | .name' | head -1)
[[ -n "$monitor2" ]] || exit 0

workspace2=$(hyprctl monitors -j | jq -r --arg monitor "$monitor2" '.[] | select(.name == $monitor) | .activeWorkspace.id')
[[ "$workspace2" -ge 0 ]] || exit 0

hyprctl dispatch "hl.dsp.workspace.swap_monitors({ monitor1 = \"$monitor1\", monitor2 = \"$monitor2\" })"
hyprctl dispatch "hl.dsp.focus({ monitor = \"$monitor2\" })"
